import React from 'react';
import type { Metadata } from 'next';

import { Header } from '@/components/Header';
import { Menu } from '@/components/Menu';

import './layout.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="main">
      <Header />
      <div className="app-content">
        <Menu />
        <main className="page-content">{children}</main>
      </div>
    </div>
  );
}
