import React from 'react';
import type { Metadata } from 'next';

import { Header } from '@/components/Header';
import { Menu } from '@/components/Menu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="main">
      <Header />
      <div className="content">
        <Menu />
        {children}
      </div>
    </div>
  );
}
