import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Header } from '@/components/Header';

import './globals.css';

const euclid = localFont({
  src: [
    {
      path: './../assets/fonts/Euclid Circular A Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './../assets/fonts/Euclid Circular A Light Italic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: './../assets/fonts/Euclid Circular A Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../assets/fonts/Euclid Circular A Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './../assets/fonts/Euclid Circular A Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './../assets/fonts/Euclid Circular A Medium Italic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: './../assets/fonts/Euclid Circular A Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './../assets/fonts/Euclid Circular A Bold Italic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={euclid.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
